/**
 * 9 Router CLI — Documentation Automation
 *
 * Automatically synchronizes documentation when the framework evolves.
 * Updates architecture docs, command docs, plugin docs, and more.
 */

import { existsSync, writeFileSync, readFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";
import type { EvolutionPlan, ChangeReport } from "./types";
import { SafetyGuard } from "./safety";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

export class DocAutomator {
  private projectRoot: string;

  constructor(_safety: SafetyGuard) {
    this.projectRoot = join(__dirname, "..", "..");
  }

  /** Update all documentation based on an evolution */
  async updateAll(plan: EvolutionPlan, report: ChangeReport): Promise<void> {
    await this.updateArchitectureDoc(plan);
    await this.updateCommandsDoc(plan);
    await this.updatePluginsDoc(plan);
    await this.updateChangeLog(report);
  }

  /** Update the architecture document */
  private async updateArchitectureDoc(plan: EvolutionPlan): Promise<void> {
    const docPath = join(this.projectRoot, "ARCHITECTURE.md");
    if (!existsSync(docPath)) return;

    let content = readFileSync(docPath, "utf-8");

    // Add new commands to the command system section
    const newCommands = plan.fileChanges
      .filter((c) => c.type === "create" && c.path.startsWith("src/commands/"))
      .map((c) => {
        const name = c.path.replace("src/commands/", "").replace(".ts", "");
        return name;
      });

    for (const cmd of newCommands) {
      if (!content.includes(`/${cmd}`)) {
        // Add to the command list
        const cmdSection = content.indexOf("## 11. Command System");
        if (cmdSection >= 0) {
          const insertPoint = content.indexOf("```", cmdSection);
          if (insertPoint >= 0) {
            const beforeEnd = content.indexOf("```", insertPoint + 3);
            if (beforeEnd >= 0) {
              const newEntry = `/${cmd} [args]           — Auto-generated by skill evolution\n`;
              content = content.slice(0, beforeEnd) + newEntry + content.slice(beforeEnd);
            }
          }
        }
      }
    }

    writeFileSync(docPath, content);
  }

  /** Update command documentation */
  private async updateCommandsDoc(plan: EvolutionPlan): Promise<void> {
    const docsDir = join(this.projectRoot, "docs");
    if (!existsSync(docsDir)) {
      mkdirSync(docsDir, { recursive: true });
    }

    const docPath = join(docsDir, "commands.md");
    let content = "";

    if (existsSync(docPath)) {
      content = readFileSync(docPath, "utf-8");
    } else {
      content = `# Commands\n\nAuto-generated command documentation.\n\n`;
    }

    // Add new commands
    const newCommands = plan.fileChanges
      .filter((c) => c.type === "create" && c.path.startsWith("src/commands/"))
      .map((c) => {
        const name = c.path.replace("src/commands/", "").replace(".ts", "");
        const reason = c.reason;
        return `## /${name}\n\n${reason}\n\n\`\`\`\n/${name} [args]\n\`\`\`\n\n`;
      });

    if (newCommands.length > 0) {
      content += `\n---\n\n## Auto-generated (${new Date().toISOString()})\n\n`;
      content += newCommands.join("\n");
      writeFileSync(docPath, content);
    }
  }

  /** Update plugin documentation */
  private async updatePluginsDoc(plan: EvolutionPlan): Promise<void> {
    const docsDir = join(this.projectRoot, "docs");
    if (!existsSync(docsDir)) {
      mkdirSync(docsDir, { recursive: true });
    }

    const docPath = join(docsDir, "plugins.md");
    let content = "";

    if (existsSync(docPath)) {
      content = readFileSync(docPath, "utf-8");
    } else {
      content = `# Plugin System\n\nAuto-generated plugin documentation.\n\n`;
    }

    // Add new plugin APIs
    const newApis = plan.fileChanges
      .filter((c) => c.type === "create" && c.path.startsWith("src/plugins/"))
      .map((c) => {
        const name = c.path.replace("src/plugins/", "").replace(".ts", "");
        return `### ${name}\n\n${c.reason}\n\n`;
      });

    if (newApis.length > 0) {
      content += `\n---\n\n## Auto-generated (${new Date().toISOString()})\n\n`;
      content += newApis.join("\n");
      writeFileSync(docPath, content);
    }
  }

  /** Update the changelog */
  private async updateChangeLog(report: ChangeReport): Promise<void> {
    const docPath = join(this.projectRoot, "CHANGELOG.md");
    let content = "";

    if (existsSync(docPath)) {
      content = readFileSync(docPath, "utf-8");
    }

    const date = new Date(report.timestamp).toISOString().split("T")[0];
    const entry = [
      `## ${date} — ${report.operation}`,
      "",
      ...report.filesCreated.map((f) => `- Added: \`${f}\``),
      ...report.filesModified.map((f) => `- Modified: \`${f}\``),
      ...report.filesDeleted.map((f) => `- Deleted: \`${f}\``),
      "",
      ...report.newCapabilities.map((c) => `- New: ${c}`),
      ...report.breakingChanges.map((c) => `- ⚠️ ${c}`),
      "",
      "---",
      "",
    ].join("\n");

    content = entry + content;
    writeFileSync(docPath, content);
  }
}
